# Generated by Django 5.2.8 on 2025-11-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('total_orphans', models.PositiveIntegerField(default=0)),
                ('boys_count', models.PositiveIntegerField(default=0)),
                ('girls_count', models.PositiveIntegerField(default=0)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='orphanage_banners/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orphanage_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
