# Generated by Django 5.2.8 on 2025-11-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('education', 'Education'), ('medical', 'Medical'), ('others', 'Others')], default='others', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='orphanage.orphanageprofile')),
            ],
        ),
    ]
